### ISSUE TITLE
Creating account through registration

### ISSUE THREAD

**Issue by alvyn279** [FozAhm/quill#1]
An account will be created for the user upon completion of registration.

- Email/password format
- After registration, they can log into their personal account and view their profile
- Be able to edit registration information until registration is closed
- Confirmation email

**Comment by alvyn279** [comment]
@FozAhm Should we keep the process of email verification, as seen below?

![image](https://user-images.githubusercontent.com/29107916/44922608-d1c2f980-ad13-11e8-8341-b5fe169289c1.png)

If so we would require a mock email server.

**Comment by FozAhm** [comment]
I think it would be a good idea to verify the email, we want make sure the email is legit and that they entered the right one
And yeah Look up Amazon SES, they have more than enough mail service for us

**Comment by alvyn279** [comment]
With email system set up already, the user can now register on the system appropriately if the registration period is open. Done.
