### ISSUE TITLE
Setup of production environment 

### ISSUE THREAD

**Issue by alvyn279** [FozAhm/quill#10]
- Create VM on North Virginia region on AWS (to be used for SES)
- Install dependencies such as node, gcc, and mongoDB
- Run application
- Create startup bash scripts
- Set up SES (#9)
- Set up cron jobs in AWS console for periodic VM image saving
- Separate sensitive information to be git-ignored from production code

**Comment by FozAhm** [comment]
https://n2ws.com/blog/how-to-guides/automate-amazon-ec2-instance-backup

I like this article, we should use this to backup the instance every day but I think it will reboot the machine every time, does reboots to the machine bring down the website? I feel like other than backing up the DB we should have point in time recovery of the entire website.
