### ISSUE TITLE
Color Schema

### ISSUE THREAD

**Issue by FozAhm** [FozAhm/quill#31]
There are still a lot of places the color seems off. Within the navigation the text is purple and pink, is there a way to make it into another color.

<img width="863" alt="screen shot 2018-10-17 at 9 57 01 pm" src="https://user-images.githubusercontent.com/25251550/47126711-bc6c4500-d257-11e8-9e7d-88ac7c6f374c.png">

Also how can we modify the email template so we do not have empty image on the header and instead the header image of the facebook event or something, also the email has a color theme that is kinda off:

<img width="610" alt="screen shot 2018-10-17 at 9 59 42 pm" src="https://user-images.githubusercontent.com/25251550/47126775-18cf6480-d258-11e8-9a3f-737c510801ec.png">

And lastly the facebook link in the email should link to our FB event.

**Comment by alvyn279** [comment]
Done in PR #33 .
