### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by qiqi0725** [FozAhm/quill#5]
#3 

- Replace current registration form with a new landing page
- Sections:
  - About
  - Schedule (Future)
  - Sponsors
  - FAQ
  - Contact

**Comment by alvyn279** [comment]
Missing things in this issue:

- Routing / to home page
- Styling with new logo, font, and colors

**Comment by alvyn279** [comment]
![image](https://user-images.githubusercontent.com/29107916/45654795-3c618c80-baab-11e8-9328-3e62e9eebee0.png)

Remove 'Register' when user is logged in.

**Comment by alvyn279** [comment]
Make cursor become a pointer when hovering logo on login page.

**Comment by alvyn279** [comment]
Resolved. Logo will be inserted later on.
